apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: domain-bot-stackoverflow-poller
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: domain-bot-stackoverflow-poller
            image: 
            imagePullPolicy: Always
            env:
            - name: DISCOVERY_ENVIRONMENT_ID
              value: 
            - name: DISCOVERY_COLLECTION_ID
              value: 
            - name: DISCOVERY_PASSWORD
              value: 
            - name: DISCOVERY_USERNAME
              value: 
            - name: SECONDS_BETWEEN_REQUESTS
              value: '1'
            - name: QUERY_DAYS_PAST
              value: '30'
            - name: TAGS
              value: istio,kubernetes
            - name: STACKEXCHANGE_ACCESS_TOKEN
              value: 
            - name: STACKEXCHANGE_API_KEY
              value: 
            args:
          restartPolicy: OnFailure